from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login, name="login"),
    path('login', views.login, name="login"),
    path('signup', views.signup, name="signup"),
    path('signupu', views.signupu, name="signupu"),
    path('admin_home', views.admin_home, name='admin_home'),
    path('view_turfs', views.view_approved_turf, name='view_approved_turf'),
    path('pending_turf', views.view_pending_turf, name='view_pending_turf'),
    path('feedbacks', views.view_feedback, name='view_feedback'),
    path('turf_home', views.turf_home, name='turf_home'),
    path('register_comp', views.register_comp, name='register_comp'),
    path('add_comp', views.add_comp, name='add_comp'),
    path('view_comp', views.view_comp, name='view_comp'),
    path('upload_adv/<int:id>', views.upload_adv, name='upload_adv'),
    path('add_adv', views.add_adv, name='add_adv'),
    path('view_adv/<int:id>', views.view_adv, name='view_adv'),
    path('edit_comp/<int:id>', views.edit_comp, name='edit_comp'),
    path('update_comp/<int:id>', views.update_comp, name='update_comp'),
    path('delete_comp/<int:id>', views.delete_comp, name='delete_comp'),
    path('register_team/<int:id>', views.register_team, name='register_team'),
    path('add_team', views.add_team, name='add_team'),
    path('view_team/<int:id>', views.view_team, name='view_team'),
    path('edit_team/<int:id>', views.edit_team, name='edit_team'),
    path('update_team/<int:id>', views.update_team, name='update_team'),
    path('delete_team/<int:id>', views.delete_team, name='delete_team'),
    path('make_pool/<int:id>', views.make_pool, name='make_pool'),
    path('register_match', views.register_match, name='register_match'),
    path('add_match', views.add_match, name='add_match'),
    path('view_match', views.view_match, name='view_match'),
    path('edit_match/<int:id>', views.edit_match, name='edit_match'),
    path('update_match/<int:id>', views.update_match, name='update_match'),
    path('delete_match/<int:id>', views.delete_match, name='delete_match'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('update_profile', views.update_profile, name='update_profile'),
    path('edit_pending_turf_status', views.edit_pending_turf_status, name='edit_pending_turf_status'),
    path('reject_pending_turf_status', views.reject_pending_turf_status, name='reject_pending_turf_status'),
    path('feedback', views.feedback, name='feedback'),
    path('sendfb', views.sendfb, name='sendfb'),
    path('view_fb', views.view_fb, name='view_fb'),
    path('user_home', views.user_home, name='user_home'),
    path('sendfb_user', views.sendfb_user, name='sendfb_user'),
    path('feedback_user', views.feedback_user, name='feedback_user'),
    path('view_fb_user', views.view_fb_user, name='view_fb_user'),
    path('view_pool/<int:id>', views.view_pool, name='view_pool'),
    path('make_match_of_pool/<int:id>', views.make_match_of_pool, name='make_match_of_pool'),
    path('view_match_of_pool/<int:id>', views.view_match_of_pool, name='view_match_of_pool'),
    path('user_view_turfs', views.user_view_turfs, name='user_view_turfs'),
    path('user_view_competition/<str:id>', views.user_view_competition, name='user_view_competition'),
    path('user_view_team/<int:id>', views.user_view_team, name='user_view_team'),
    path('user_view_adv/<int:id>', views.user_view_adv, name='user_view_adv'),
    path('user_view_pool/<int:id>', views.user_view_pool, name='user_view_pool'),
    path('user_view_match_of_pool/<int:id>', views.user_view_match_of_pool, name='user_view_match_of_pool'),
    path('add_members/<int:id>', views.add_members, name='add_members'),
    path('members_add', views.members_add, name='members_add'),
    path('view_members/<int:id>', views.view_members, name='view_members'),
    path('delete_member/<int:id>', views.delete_member, name ='delete_member'),
    path('user_rate_turf/<str:id>', views.user_rate_turf, name='user_rate_turf'),
    path('rate/<str:id>',views.rate, name='rate'),
    path('user_view_competitions/<str:id>',views.user_view_competitions, name='user_view_competitions'),
    path('user_view_members/<int:id>', views.user_view_members, name='user_view_members'),
    path('location/<str:id>/<str:jd>', views.location, name='location'),

]